# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-titles-from-headings

permalink: pretty

# COLLECTIONS
collections:
  time:
    output: true
    title: Time
defaults:
  - scope:
      type: time
    values:
      layout: default
      weight: 1

# CSS
# css:
#   font:
#     size: 15px
#     color: Black
#   link:
#     color: MediumBlue
#   html:
#     background: Gainsboro
#   main:
#     background: White
#   width: 100%
#   navigation:
#     background: Gainsboro
#     hover:
#       background: Whitesmoke