# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-titles-from-headings

permalink: pretty

# CSS
# css:
#   font:
#     size: 15px
#     color: Black
#   body:
#     background: Gainsboro
#   main:
#     background: White
#   max_width: 100%