name: Buongiorno
on:
  schedule:
    - cron: '1 0 * * *'
jobs:
  buongiorno:
    name: buongiorno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: Stockopedia/octommit
        id: goodmorning
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            octommit.update()
              .org("riminino")
              .repository("barebone")
              .sourceBranch("master")
              .outputBranch("master")
              .sourcePath("_data/buongiorno.yml")
              .outputPath("_data/buongiorno.yml")
              .set("today", new Date().toString())
              .commit("Buongiorno commit")
              .run();
