name: Buongiorno
on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Fetch and save time
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://worldtimeapi.org/api/timezone/Europe/Rome'
          file: '_data/buongiorno.json'
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
